imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }

    translator: { fallback: en }
    default_locale:  en

    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        currencyService: "@currencyService"
        accommodationService: "@accommodationService"
        permissionsService: "@permissionsService"
        locationService: "@locationService"
        emailService: "@emailService"
        bookingService: "@bookingService"
        messageService: "@messageService"
        languageService: "@languageService"
        statService: "@statService"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:            smtp
    username:             ~
    password:             ~
    host:                 localhost
    port:                 false
    encryption:           ~
    auth_mode:            ~
    spool:
        type:                 file
        path:                 "%kernel.cache_dir%/swiftmailer/spool"
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_address:     ~
    disable_delivery:     ~
    logging:              "%kernel.debug%"


lexik_translation:
    fallback_locale: en      # (required) default locale to use
    managed_locales: [en, hr, de, fr, it, es, cs, sl, pl, hu, ru, pt, nl, da, sv, sk, no, fi, ca, sr, mk, bs, tr, ja, zh]    # (required) locales that the bundle have to manage

    base_layout:     "LexikTranslationBundle::layout.html.twig" # layout used with the translation edition template
    use_yml_tree:    false    # if "true" we will print a nice tree in the yml source files. It is a little slower.
    grid_input_type: text     # define field type used in the grid (text|textarea)

    storage:
        type: orm                    # where to store translations: "orm", "mongodb" or "propel"
#        object_manager: something    # The name of the entity / document manager which uses different connection (see: http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html)
                                         # When using propel, this can be used to specify the propel connection name

    resources_registration:
        type:                 all     # resources type to register: "all", "files" or "database"
        managed_locales_only: true    # will only load resources for managed locales


jms_i18n_routing:
    default_locale: en
    locales: [en, hr, de, it, es, fr, cs, sl, pl, hu, ru, pt, nl, da, sv, sk, no, fi, ca, sr, mk, bs, tr, ja, zh]
    strategy: prefix_except_default

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [275, 150], mode: outbound }
        my_thumb_blog:
            quality: 75
            filters:
                thumbnail: { size: [275, 200], mode: outbound }
        my_thumb_slider-single-small:
            quality: 75
            filters:
                thumbnail: { size: [90, 65], mode: outbound }
        my_thumb_slider-single-big:
            quality: 75
            filters:
                thumbnail: { size: [560, 380], mode: outbound }


mz_mail_chimp:
    api_key: 3ca9a5af3fbb83b4223379a99bea3a48-us11
    default_list: d4634b2d80
    ssl: true #option to use http or https