admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: UserBundle:Base:login }

login_check:
    path: /login_check

logout:
    path:   /logout

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translate

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"