security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_ADMIN, ROLE_GUEST, ROLE_HOST ]
        ROLE_HOST:        ROLE_HOST
        ROLE_GUEST:       ROLE_GUEST

    providers:
        administrators:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /profile
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/[a-z]+/admin, roles: ROLE_ADMIN }
        - { path: ^/translate, roles: ROLE_ADMIN }
        - { path: ^/[a-z]+/translate, roles: ROLE_ADMIN }
        - { path: ^/profile/accommodations, roles: ROLE_HOST }
        - { path: ^/[a-z]+/profile/accommodations, roles: ROLE_HOST }
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/[a-z]+/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/messages, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/[a-z]+/messages, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/wishlist, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/[a-z]+/wishlist, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/accommodations, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/[a-z]+/accommodations, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/accommodation/edit, roles: ROLE_HOST }
        - { path: ^/[a-z]+/accommodation/edit, roles: ROLE_HOST }
        - { path: ^/accommodation/new, roles: ROLE_HOST }
        - { path: ^/[a-z]+/accommodation/new, roles: ROLE_HOST }
        - { path: ^/accommodation/delete, roles: ROLE_HOST }
        - { path: ^/[a-z]+/accommodation/delete, roles: ROLE_HOST }
        - { path: ^/unit, roles: ROLE_HOST }
        - { path: ^/[a-z]+/unit, roles: ROLE_HOST }
        - { path: ^/[a-z]+/specialOffer/list, roles: ROLE_HOST }
        - { path: ^/specialOffer/list, roles: ROLE_HOST }
        - { path: ^/[a-z]+/specialOffer/new, roles: ROLE_HOST }
        - { path: ^/specialOffer/new, roles: ROLE_HOST }
        - { path: ^/[a-z]+/specialOffer/edit, roles: ROLE_HOST }
        - { path: ^/specialOffer/edit, roles: ROLE_HOST }
        - { path: ^/[a-z]+/unit, roles: ROLE_HOST }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


    access_denied_url: /403