<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository {

    /**
     * Get all Cities
     * @return array
     */
    public function getAll() {
        $qb = $this->createQueryBuilder('ci')
            ->select('ci, sr, co, r')
            ->leftJoin('ci.subregion', 'sr')
            ->innerJoin('ci.region', 'r')
            ->innerJoin('r.country', 'co');

        return $qb->getQuery()->getResult();
    }

    public function getAllFast() {
        $qb = $this->createQueryBuilder('ci')
            ->select('ci, sr, co, r')
            ->leftJoin('ci.subregion', 'sr')
            ->innerJoin('ci.region', 'r')
            ->innerJoin('r.country', 'co')
            ->setMaxResults(5000);

        return $qb->getQuery()->getArrayResult();
    }

    public function getByEn($en) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.en = :en')
            ->setParameter('en', $en);

        return (count($qb->getQuery()->getResult()) == 0) ? false : $qb->getQuery()->getSingleResult();
    }

    /**
     * Get cities by subregionId
     * @param $subregionId
     * @return array
     */
    public function getBySubregion($subregionId) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.subregion = :subregionId')
            ->setParameter('subregionId', $subregionId);
        return $qb->getQuery()->getResult();
    }

    /**
     * Get cities by regionId
     * @param $subregionId
     * @return array
     */
    public function getByRegion($regionId) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.region = :regionId')
            ->setParameter('regionId', $regionId);
        return $qb->getQuery()->getResult();
    }

    /**
     * Search autocomplete by string
     * @param $string
     * @return array
     */
    public function searchCityByString($string) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.en like :string')
            ->orWhere('c.hr like :string')
            ->orWhere('c.de like :string')
            ->orWhere('c.it like :string')
            ->orWhere('c.es like :string')
            ->orWhere('c.fr like :string')
            ->orWhere('c.cs like :string')
            ->orWhere('c.sl like :string')
            ->orWhere('c.pl like :string')
            ->orWhere('c.hu like :string')
            ->orWhere('c.ru like :string')
            ->orWhere('c.pt like :string')
            ->orWhere('c.nl like :string')
            ->orWhere('c.da like :string')
            ->orWhere('c.sv like :string')
            ->orWhere('c.sk like :string')
            ->orWhere('c.no like :string')
            ->orWhere('c.fi like :string')
            ->orWhere('c.ca like :string')
            ->orWhere('c.sr like :string')
            ->orWhere('c.mk like :string')
            ->orWhere('c.bs like :string')
            ->orWhere('c.tr like :string')
            ->orWhere('c.ja like :string')
            ->orWhere('c.zh like :string')
            ->setParameter('string', '%' . $string . '%')
            ->setMaxResults(20);

        return $qb->getQuery()->getResult();
    }

}
