<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository {

	public function getByCode($code) {
		$qb = $this->createQueryBuilder('c')
		           ->select('c')
		           ->where('c.code = :code')
		           ->setParameter('code', $code);

		return $qb->getQuery()->getSingleResult();
	}

}
