<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiscoverRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoverRepository extends EntityRepository {

    public function getNumByStatus($status) {
        $qb = $this->createQueryBuilder('so')
            ->select('so')
            ->where('so.status = :status')
            ->setParameter('status', $status);

        return count($qb->getQuery()->getResult());
    }

}
