<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository {

    public function getGallery($accommodationId) {
        $qb = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.accommodation = :accommodationId')
            ->setParameter('accommodationId', $accommodationId);

        return $qb->getQuery()->getResult();
    }

}
