<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {

    /**
     * Get all posts by language
     * @param $lang
     * @return array
     */
    public function getByLang($lang) {
        $qb = $this->createQueryBuilder('p')
            ->select('p, c')
            ->innerJoin('p.language', 'l')
            ->leftJoin('p.comments', 'c')
            ->where('l.code = :lang')
            ->setParameter('lang', $lang)
            ->orderBy('p.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Find all parent posts (lang == en)
     * @return array
     */
    public function findParents() {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->innerJoin('p.language', 'l')
            ->where('l.code = :code')
            ->setParameter('code', 'en');

        return $qb->getQuery()->getResult();
    }

}
