<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriceExtraRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceExtraRepository extends EntityRepository {


    public function getNotSelected($unit) {
        $qb = $this->createQueryBuilder('pe')
            ->select('pe')
            ->where('NOT EXISTS(
                SELECT 1 FROM AppBundle:PriceExtra AS priceExtra
                INNER JOIN priceExtra.unitPriceExtra AS unitPriceExtra
                WHERE unitPriceExtra.unit = :unit AND unitPriceExtra.priceExtra = priceExtra
            )')
            ->setParameter('unit', $unit);

        return $qb->getQuery()->getResult();
    }


    public function getSelected($unit) {
        $qb = $this->createQueryBuilder('pe')
            ->select('pe')
            ->innerJoin('pe.unitPriceExtra', 'upe')
            ->where('upe.unit = :unit')
            ->setParameter('unit', $unit);

        return $qb->getQuery()->getResult();
    }

}
