<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository {

    /**
     * Get all Regions
     * @return array
     */
    public function getAll() {
        $qb = $this->createQueryBuilder('r')
            ->select('r, c')
            ->innerJoin('r.country', 'c');
        return $qb->getQuery()->getResult();
    }

    public function getByHr($hr) {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.hr = :hr')
            ->setParameter('hr', $hr);
        return $qb->getQuery()->getSingleResult();
    }

    public function getByEn($en) {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.en = :en')
            ->setParameter('en', $en);

        return (count($qb->getQuery()->getResult()) == 0) ? false : $qb->getQuery()->getSingleResult();
    }

    /**
     * get Region by CountryId
     * @param $countryId
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByCountry($countryId) {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.country = :countryId')
            ->setParameter('countryId', $countryId);
        return $qb->getQuery()->getResult();
    }

    /**
     * Search autocomplete by string
     * @param $string
     * @return array
     */
    public function searchRegionByString($string) {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.en like :string')
            ->orWhere('r.hr like :string')
            ->orWhere('r.de like :string')
            ->orWhere('r.it like :string')
            ->orWhere('r.es like :string')
            ->orWhere('r.fr like :string')
            ->orWhere('r.cs like :string')
            ->orWhere('r.sl like :string')
            ->orWhere('r.pl like :string')
            ->orWhere('r.hu like :string')
            ->orWhere('r.ru like :string')
            ->orWhere('r.pt like :string')
            ->orWhere('r.nl like :string')
            ->orWhere('r.da like :string')
            ->orWhere('r.sv like :string')
            ->orWhere('r.sk like :string')
            ->orWhere('r.no like :string')
            ->orWhere('r.fi like :string')
            ->orWhere('r.ca like :string')
            ->orWhere('r.sr like :string')
            ->orWhere('r.mk like :string')
            ->orWhere('r.bs like :string')
            ->orWhere('r.tr like :string')
            ->orWhere('r.ja like :string')
            ->orWhere('r.zh like :string')
            ->setParameter('string', '%' . $string . '%')
            ->setMaxResults(20);

        return $qb->getQuery()->getResult();
    }
}
