<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitGalleryRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitGalleryRepository extends EntityRepository {

    public function getGallery($unitId) {
        $qb = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.unit = :unitId')
            ->setParameter('unitId', $unitId);

        return $qb->getQuery()->getResult();
    }

}
