<?php

namespace UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {

    /**
     * Get roles for user registration, not all roles
     * @return array
     */
    public function getRolesRegistration() {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.role != :role1')
            ->setParameter('role1', 'ROLE_ADMIN')
            ->orderBy('r.name', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
